version: '3.9'
services:
  postgres:
    image: postgres:15.3
    container_name: corporation-api-db
    build:
      dockerfile: ./db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: corporation-api
      POSTGRES_USER: corporation-api-user
      POSTGRES_PASSWORD: corporation-api-pw
  api:
    container_name: corporation-api
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres